name: Atualizar README com Contribuições

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install node-fetch@2 fs

      - name: Rodar o script para atualizar README
        env:
          TOKEN_ACCESS: ${{ secrets.TOKEN_ACCESS }}
        run: node update-readme.js

      - name: Commit e push se houver mudanças
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualizando README com novas contribuições" || exit 0
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN_ACCESS }}@github.com/Munardt/md.git
          git push

